import type { Metadata } from 'next'
import { NextIntlClientProvider, useMessages } from 'next-intl';
import '../globals.css'

export const metadata: Metadata = {
  title: 'University Map',
  description: 'Generated by create next app',
}

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode,
  params: { locale: string }
}) {
  const messages = useMessages();

  return (
    <html suppressHydrationWarning={true} lang={locale}>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <body>{children}</body>
      </NextIntlClientProvider>
    </html>
  )
}
