import type { Metadata } from 'next';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { ColorSchemeScript, MantineProvider } from '@mantine/core';
import SideNavbar from '@/components/Nav/SideNavbar';
import '@mantine/core/styles.css';
import '@mantine/carousel/styles.css';
import '../globals.css';

export const metadata: Metadata = {
  title: 'University Map',
  description: 'Generated by create next app',
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode,
  params: { locale: string }
}) {
  const messages = useMessages();

  return (
    <html suppressHydrationWarning={true} lang={locale}>
      <head>
        <ColorSchemeScript />
      </head>
      <NextIntlClientProvider locale={locale} messages={messages}>
        <body>
          <MantineProvider>
            <div style={{ height: '100vh', display: 'flex' }}>
              <SideNavbar />
              <div style={{ height: '100%', flexGrow: 1, paddingLeft: '50px' }}>
                {children}
              </div>
            </div>
          </MantineProvider>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
